- name: raspbian-statusboard
  hosts: pi
  tasks:

    - name: remount rw
      raw: mount -o remount,rw /

    # taken from https://github.com/asb/raspi-config/blob/master/raspi-config
    - name: enable Raspbian Desktop
      shell: >
        update-rc.d lightdm enable 2 &&
        sed /etc/lightdm/lightdm.conf -i -e "s/^#autologin-user=.*/autologin-user=pi/" &&
        rm -f /etc/profile.d/raspi-config.sh &&
        sed -i /etc/inittab -e "s/^#\(.*\)#\s*RPICFG_TO_ENABLE\s*/\1/" -e "/#\s*RPICFG_TO_DISABLE/d" &&
        telinit q

    - name: modify lightdm.conf
      lineinfile: dest=/etc/lightdm/lightdm.conf regexp="^#xserver-command=" line="xserver-command=X -s 0 dpms" state=present

    - name: install unclutter
      apt: package=unclutter state=present

    - name: install defaults
      copy: src=files/default dest=/etc/default/raspbian-statusboard mode=0644 owner=root group=root

    - name: install raspbian-statusboard
      copy: src=files/raspbian-statusboard dest=/usr/local/bin/raspbian-statusboard mode=0755 owner=root group=root

    - name: install LXDE autostart
      copy: src=files/autostart dest=/etc/xdg/lxsession/LXDE/autostart mode=0644 owner=root group=root

    - name: copy shift_state.c
      copy: src=files/shift_state.c dest=/tmp/ mode=0644 owner=root group=root

    - name: build shift_state
      command: gcc -o /usr/local/bin/shift_state shift_state.c

    # for wpa_cli_web
    - name: install ruby-dev
      apt: package=ruby-dev state=present

    - name: install wpa_cli_web
      gem: name=wpa_cli_web state=latest

