- name: raspbian-statusboard
  hosts: pi
  gather_facts: false
  tasks:

    - name: remount rw
      raw: mount -o remount,rw {{item}}
      with_items:
        - /
        - /etc
        - /home
        - /var

    # taken from https://github.com/asb/raspi-config/blob/master/raspi-config
    - name: enable Raspbian Desktop
      shell: >
        update-rc.d lightdm enable 2 &&
        sed /etc/lightdm/lightdm.conf -i -e "s/^#autologin-user=.*/autologin-user=pi/" &&
        rm -f /etc/profile.d/raspi-config.sh &&
        sed -i /etc/inittab -e "s/^#\(.*\)#\s*RPICFG_TO_ENABLE\s*/\1/" -e "/#\s*RPICFG_TO_DISABLE/d" &&
        telinit q

    - name: modify lightdm.conf
      lineinfile: dest=/etc/lightdm/lightdm.conf regexp="^#xserver-command=" line="xserver-command=X -s 0 dpms" state=present

    - name: install {{item}}
      apt: package={{item}} state=present
      with_items:
        - unclutter
        - chromium-browser

    - name: install defaults
      copy: src=files/default dest=/etc/default/raspbian-statusboard mode=0644 owner=root group=root

    - name: install raspbian-statusboard init script
      copy: src=files/raspbian-statusboard.init dest=/etc/init.d/raspbian-statusboard mode=0755 owner=root group=root

    - name: install raspbian-statusboard bin
      copy: src=files/raspbian-statusboard dest=/usr/bin/raspbian-statusboard mode=0755 owner=root group=root

    - name: install LXDE autostart
      copy: src=files/autostart dest=/etc/xdg/lxsession/LXDE/autostart mode=0644 owner=root group=root

    - name: copy shift_state.c
      copy: src=files/shift_state.c dest=/tmp/ mode=0644 owner=root group=root

    - name: build shift_state
      command: gcc -o /usr/bin/shift_state /tmp/shift_state.c

    # for raspbian-statusboard-web dependencies
    - name: install ruby-dev
      apt: package=ruby-dev state=present

    # for specific_install
    - name: update rubygems
      shell: REALLY_GEM_UPDATE_SYSTEM=1 gem update --system

    - name: install specific_install
      gem: name=specific_install state=present

    - name: install raspbian-statusboard-web
      command: gem specific_install https://github.com/goodeggs/raspbian-statusboard-web.git

    - name: reboot
      command: reboot

    - name: wait for reboot
      pause: seconds=30

    - name: wait for ssh
      local_action: wait_for host={{inventory_hostname}} port=22 timeout=60 state=started
      sudo: false

