#!/bin/sh
. /etc/default/raspbian-statusboard

# http://stackoverflow.com/questions/13657889/check-if-the-shift-key-is-currently-being-held-in-the-linux-text-fb-console
state=`shift_state` && if [ $(($state & 1)) -eq 1 ]; then
  
  mount -o remount,rw /
  mount -o remount,rw /etc
  RACK_ENV=production wpa_cli_web -p 3000 start 2>&1 >> /var/log/wpa_cli_web.log &
  STATUSBOARD_URL="http://localhost:3000"
fi

eval \$STATUSBOARD_BIN $STATUSBOARD_ARGS
